=== shinarlanza/XML/people.dtd
<!ELEMENT people (person+)>
<!ELEMENT person (name, age, sex, bday, address)>
<!ELEMENT name (Fname,Lname)>
<!ELEMENT bday (month,day,year)>
<!ELEMENT address (city, province, town)>
<!ELEMENT Fname (#PCDATA)>
<!ELEMENT Lname (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT sex (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT province (#PCDATA)>
<!ELEMENT town (#PCDATA)>

=== shinarlanza/XML/people.xml
<?xml version = "1.0" encoding = "utf-8"?>
<?xml-stylesheet type="text/xsl" href="people.xsl"?>

<!DOCTYPE people SYSTEM "people.dtd">


<people>
	<person>
		<name> 

			<Fname>Joshua Andrei</Fname>
			<Lname>Ventura</Lname>

		</name>

		<age>21</age>

		<sex>male</sex>

		<bday>
			<month>04</month>
			<day>26</day>
			<year>2000</year>
		</bday>

		<address>
			<city>n.a</city>
			<province>Aklan</province>
			<town>Kalibo</town>
		</address>

	</person>

	<person>
		
		<name>
			<Fname>Elmar Cris</Fname>
			<Lname>Garcia</Lname>
		</name>

		<age>21</age>

		<sex> male </sex>

		<bday>
			<month>06</month>
			<day>21</day>
			<year>2000</year>
		</bday>

		<address>
			<city>n.a</city>
			<province>Antique</province>
			<town>Culasi</town>
		</address>

	</person>

		<person>
		
		<name>
			<Fname>Albert Anthony</Fname>
			<Lname>Polong</Lname>
		</name>

		<age>21</age>

		<sex> male </sex>

		<bday>
			<month>03</month>
			<day>04</day>
			<year>2000</year>
		</bday>

		<address>
			<city>n.a</city>
			<province>Antique</province>
			<town>Tobias Fornier</town>
		</address>

	</person>

	<person>
		
		<name>
			<Fname>Sheina</Fname>
			<Lname>Arlanza</Lname>
		</name>

		<age>21</age>

		<sex> female </sex>

		<bday>
			<month>11</month>
			<day>19</day>
			<year>2000</year>
		</bday>

		<address>
			<city>Passi</city>
			<province>Iloilo</province>
			<town>n.a</town>
		</address>

	</person>

	<person>
		
		<name>
			<Fname>J-Anne</Fname>
			<Lname>Soliva</Lname>
		</name>

		<age>21</age>

		<sex> female </sex>

		<bday>
			<month>06</month>
			<day>02</day>
			<year>2000</year>
		</bday>

		<address>
			<city>n.a.</city>
			<province>Iloilo</province>
			<town>San Joaquin</town>
		</address>

	</person>

	<person>
		
		<name>
			<Fname>Will Ann Grace</Fname>
			<Lname>Teves</Lname>
		</name>

		<age>21</age>

		<sex> female </sex>

		<bday>
			<month>12</month>
			<day>14</day>
			<year>2000</year>
		</bday>

		<address>
			<city>n.a</city>
			<province>Iloilo</province>
			<town>Guimbal</town>
		</address>

	</person>

	<person>
		
		<name>
			<Fname>Jhemes Cris</Fname>
			<Lname>Colas</Lname>
		</name>

		<age>21</age>

		<sex> male </sex>

		<bday>
			<month>12</month>
			<day>08</day>
			<year>2000</year>
		</bday>

		<address>
			<city>n.a</city>
			<province>Aklan</province>
			<town>Kalibo</town>
		</address>

	</person>

	<person>
		
		<name>
			<Fname>Charles</Fname>
			<Lname>Villafuerte</Lname>
		</name>

		<age>21</age>

		<sex> male </sex>

		<bday>
			<month>04</month>
			<day>28</day>
			<year>2000</year>
		</bday>

		<address>
			<city>n.a</city>
			<province>Iloilo</province>
			<town>Banate</town>
		</address>

	</person>

	<person>
		
		<name>
			<Fname>Asther Louie</Fname>
			<Lname>Cabardo</Lname>
		</name>

		<age>21</age>

		<sex> male </sex>

		<bday>
			<month>09</month>
			<day>05</day>
			<year>2000</year>
		</bday>

		<address>
			<city>n.a</city>
			<province>Iloilo</province>
			<town>Leon</town>
		</address>

	</person>
</people>
